// Code generated by protoc-gen-go. DO NOT EDIT.
// source: controller.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "k8s.io/api/core/v1"
	math "math"
	v1alpha1 "ssd-git.juniper.net/contrail/cn2/contrail/pkg/apis/core/v1alpha1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubscriptionRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscriptionRequest) Reset()         { *m = SubscriptionRequest{} }
func (m *SubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*SubscriptionRequest) ProtoMessage()    {}
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{0}
}

func (m *SubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionRequest.Unmarshal(m, b)
}
func (m *SubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *SubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionRequest.Merge(m, src)
}
func (m *SubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_SubscriptionRequest.Size(m)
}
func (m *SubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionRequest proto.InternalMessageInfo

func (m *SubscriptionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Resource struct {
	Kind                 string   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{1}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Resource) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func init() {
	proto.RegisterType((*SubscriptionRequest)(nil), "github.com.michaelhenkel.config_controller.pkg.apis.v1.SubscriptionRequest")
	proto.RegisterType((*Resource)(nil), "github.com.michaelhenkel.config_controller.pkg.apis.v1.Resource")
}

func init() {
	proto.RegisterFile("controller.proto", fileDescriptor_ed7f10298fa1d90f)
}

var fileDescriptor_ed7f10298fa1d90f = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xc1, 0x4e, 0xeb, 0x30,
	0x10, 0x54, 0xfa, 0x9e, 0x9e, 0x5e, 0x7d, 0x2a, 0xe6, 0x52, 0x45, 0x1c, 0x50, 0x4f, 0x70, 0xe8,
	0x9a, 0x14, 0x09, 0xf5, 0x88, 0xe8, 0x81, 0x03, 0x08, 0x55, 0x45, 0x02, 0x89, 0x4b, 0xe5, 0x38,
	0x4b, 0x62, 0x92, 0xda, 0xc6, 0x76, 0xca, 0x17, 0x21, 0x7e, 0x8c, 0x0f, 0x41, 0x49, 0x49, 0xd3,
	0x56, 0x9c, 0xca, 0x29, 0xbb, 0xd9, 0x99, 0xd5, 0x78, 0x76, 0x48, 0x4f, 0x68, 0xe5, 0xad, 0x2e,
	0x0a, 0xb4, 0x60, 0xac, 0xf6, 0x9a, 0x5e, 0xa4, 0xd2, 0x67, 0x65, 0x0c, 0x42, 0x2f, 0x60, 0x21,
	0x45, 0xc6, 0xb1, 0xc8, 0x50, 0xe5, 0x58, 0x80, 0xd0, 0xea, 0x59, 0xa6, 0xf3, 0x4d, 0x46, 0x9e,
	0x02, 0x37, 0xd2, 0xc1, 0x32, 0x0a, 0xa7, 0xce, 0x25, 0xc3, 0x54, 0x7a, 0x78, 0x29, 0x95, 0x34,
	0x68, 0x41, 0xa1, 0x67, 0x35, 0x96, 0xcb, 0x82, 0x09, 0x35, 0x6a, 0x1b, 0x93, 0xa7, 0xac, 0xa2,
	0x31, 0xa1, 0x2d, 0xb2, 0x65, 0xc4, 0x0b, 0x93, 0xf1, 0x88, 0xa5, 0xa8, 0xd0, 0x72, 0x8f, 0xc9,
	0x4a, 0x49, 0x38, 0xc8, 0xc7, 0x0e, 0xa4, 0xae, 0xa0, 0x0d, 0x72, 0x17, 0x33, 0x38, 0x25, 0x87,
	0xf7, 0x65, 0xec, 0x84, 0x95, 0xc6, 0x4b, 0xad, 0x66, 0xf8, 0x5a, 0xa2, 0xf3, 0x94, 0x92, 0xbf,
	0x8a, 0x2f, 0xb0, 0x1f, 0x1c, 0x07, 0x27, 0xdd, 0x59, 0x5d, 0x0f, 0xa6, 0xe4, 0xff, 0x0c, 0x9d,
	0x2e, 0xad, 0xc0, 0x6a, 0x9e, 0x4b, 0x95, 0x34, 0xf3, 0xaa, 0x5e, 0x73, 0x3a, 0x2d, 0x87, 0x1e,
	0x91, 0x6e, 0xf5, 0x75, 0x86, 0x0b, 0xec, 0xff, 0xa9, 0x07, 0xed, 0x8f, 0xd1, 0x67, 0x87, 0xf4,
	0x26, 0xb5, 0x29, 0x93, 0xb5, 0x27, 0xf4, 0x3d, 0x20, 0xf4, 0x5b, 0x52, 0x8c, 0xb7, 0xd2, 0xf9,
	0x47, 0xee, 0x45, 0x46, 0x6f, 0x60, 0x3f, 0x5f, 0xe1, 0x87, 0xe7, 0x85, 0x97, 0xfb, 0x2e, 0x6b,
	0x0c, 0x38, 0x0b, 0xe8, 0x47, 0x40, 0x0e, 0xae, 0xd1, 0x3f, 0x48, 0xeb, 0x4b, 0x5e, 0xdc, 0xa1,
	0x7f, 0xd3, 0x36, 0xa7, 0xbf, 0xde, 0x1c, 0x4e, 0xc1, 0xb9, 0x64, 0xbe, 0x13, 0x04, 0x68, 0x6e,
	0x0f, 0x42, 0x8d, 0xda, 0x66, 0xbd, 0xa0, 0x3a, 0x2f, 0x34, 0x41, 0x80, 0x6d, 0x4d, 0x57, 0xe3,
	0xa7, 0x8d, 0x4c, 0xb2, 0x2d, 0x51, 0x6c, 0x25, 0x6a, 0xd8, 0x8a, 0x6a, 0xc3, 0xb5, 0x8c, 0xe2,
	0x7f, 0x75, 0x48, 0xce, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1f, 0xf3, 0x19, 0x33, 0xe6, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ConfigControllerClient is the client API for ConfigController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConfigControllerClient interface {
	SubscribeListWatch(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (ConfigController_SubscribeListWatchClient, error)
	GetVirtualNetwork(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*v1alpha1.VirtualNetwork, error)
}

type configControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigControllerClient(cc grpc.ClientConnInterface) ConfigControllerClient {
	return &configControllerClient{cc}
}

func (c *configControllerClient) SubscribeListWatch(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (ConfigController_SubscribeListWatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ConfigController_serviceDesc.Streams[0], "/github.com.michaelhenkel.config_controller.pkg.apis.v1.ConfigController/SubscribeListWatch", opts...)
	if err != nil {
		return nil, err
	}
	x := &configControllerSubscribeListWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ConfigController_SubscribeListWatchClient interface {
	Recv() (*Resource, error)
	grpc.ClientStream
}

type configControllerSubscribeListWatchClient struct {
	grpc.ClientStream
}

func (x *configControllerSubscribeListWatchClient) Recv() (*Resource, error) {
	m := new(Resource)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *configControllerClient) GetVirtualNetwork(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*v1alpha1.VirtualNetwork, error) {
	out := new(v1alpha1.VirtualNetwork)
	err := c.cc.Invoke(ctx, "/github.com.michaelhenkel.config_controller.pkg.apis.v1.ConfigController/GetVirtualNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigControllerServer is the server API for ConfigController service.
type ConfigControllerServer interface {
	SubscribeListWatch(*SubscriptionRequest, ConfigController_SubscribeListWatchServer) error
	GetVirtualNetwork(context.Context, *Resource) (*v1alpha1.VirtualNetwork, error)
}

// UnimplementedConfigControllerServer can be embedded to have forward compatible implementations.
type UnimplementedConfigControllerServer struct {
}

func (*UnimplementedConfigControllerServer) SubscribeListWatch(req *SubscriptionRequest, srv ConfigController_SubscribeListWatchServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeListWatch not implemented")
}
func (*UnimplementedConfigControllerServer) GetVirtualNetwork(ctx context.Context, req *Resource) (*v1alpha1.VirtualNetwork, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVirtualNetwork not implemented")
}

func RegisterConfigControllerServer(s *grpc.Server, srv ConfigControllerServer) {
	s.RegisterService(&_ConfigController_serviceDesc, srv)
}

func _ConfigController_SubscribeListWatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscriptionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigControllerServer).SubscribeListWatch(m, &configControllerSubscribeListWatchServer{stream})
}

type ConfigController_SubscribeListWatchServer interface {
	Send(*Resource) error
	grpc.ServerStream
}

type configControllerSubscribeListWatchServer struct {
	grpc.ServerStream
}

func (x *configControllerSubscribeListWatchServer) Send(m *Resource) error {
	return x.ServerStream.SendMsg(m)
}

func _ConfigController_GetVirtualNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Resource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigControllerServer).GetVirtualNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.michaelhenkel.config_controller.pkg.apis.v1.ConfigController/GetVirtualNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigControllerServer).GetVirtualNetwork(ctx, req.(*Resource))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConfigController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.michaelhenkel.config_controller.pkg.apis.v1.ConfigController",
	HandlerType: (*ConfigControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVirtualNetwork",
			Handler:    _ConfigController_GetVirtualNetwork_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeListWatch",
			Handler:       _ConfigController_SubscribeListWatch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "controller.proto",
}
